# Generated by Django 5.2.1 on 2025-07-01 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('CORDAS', 'Cordas'), ('PERCUSSÃO', 'Percussão'), ('TECLAS', 'Teclas'), ('ACESSÓRIOS', 'Acessórios'), ('ÁUDIO', 'Áudio')], default='', max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('estoque', models.IntegerField()),
                ('mais_vendido', models.BooleanField(default=False)),
                ('promocao', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('CORDAS', 'Cordas'), ('PERCUSSÃO', 'Percussão'), ('TECLAS', 'Teclas'), ('ACESSÓRIOS', 'Acessórios'), ('ÁUDIO', 'Áudio')], default='', max_length=100)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='home.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('destaque', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='home.produtos')),
            ],
        ),
    ]
