# Generated by Django 5.2.1 on 2025-07-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_produtos_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='autualizado_em',
            new_name='atualizado_em',
        ),
    ]
