# Generated by Django 5.2.1 on 2025-07-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_subcategoriaproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='home.subcategoriaproduto'),
        ),
    ]
