# Generated by Django 5.2.1 on 2025-07-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_produtos_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='nome_sem_acentos',
            field=models.CharField(default='', editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
